name: wasla
description: A new Flutter project.

publish_to: 'none'



version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'



dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  concentric_transition: ^1.0.3
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  rive: ^0.12.1
  easy_localization: ^3.0.3
  flutter_phoenix: ^1.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.4

flutter_native_splash:
  color: "#0d101c"
  image: assets/images/logo/logo.png
  android_12:
    image: assets/images/logo/500.png

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true




  assets:
    - assets/images/logo/
    - assets/images/onboarding/
    - assets/images/svg/
    - assets/animation/rive/
    - assets/translations/


  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/cairo/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/cairo/Cairo-Black.ttf
          weight: 900








