name: wasla
description: A new Flutter project.

publish_to: 'none'



version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'



dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #responsive
  flutter_screenutil: ^5.9.0

  #animation
  concentric_transition: ^1.0.3
  rive: ^0.12.3
  lottie: ^2.7.0

  #svg files (icons)
  flutter_svg: ^2.0.9

  #bloc
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  #equatable
  equatable: ^2.0.5

  #localization
  easy_localization: ^3.0.3
  flutter_phoenix: ^1.1.1 #analysis issues

  #server connection
  retrofit: ^4.0.3
  dio: ^5.3.3
  analyzer:
  internet_connection_checker: ^1.0.0+1

  #local storage
  shared_preferences: ^2.2.2

  #dependency injection
  get_it: ^7.6.4

  #code generators
  json_annotation:
  freezed_annotation: ^2.4.1

  #left or right return
  dartz: ^0.10.1

  #for matrix clipping
  vector_math:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.5
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  retrofit_generator: ^8.0.3
  flutter_lints: ^3.0.1
  pretty_dio_logger: ^1.3.1
  freezed: ^2.4.5

flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#07161B"
  image: assets/images/logo/logo.png
  android_12:
    image: assets/images/logo/logo_500.png




flutter:
  uses-material-design: true




  assets:
    - assets/images/logo/
    - assets/images/onboarding/
    - assets/images/background/
    - assets/images/svg/
    - assets/animation/rive/
    - assets/animation/json/
    - assets/translations/


  fonts:
    #arabic font family
    - family: cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/cairo/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/cairo/Cairo-Black.ttf
          weight: 900

    #english font family
    - family: gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/gilroy/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/gilroy/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/gilroy/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/gilroy/Gilroy-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/gilroy/Gilroy-Black.ttf
          weight: 900








